### ISSUE TITLE
zwally vs. icesat basins

### ISSUE THREAD

**Issue by talbrecht** [pism/pism-ais#4]
Please update link for Zwally basins. What is the difference between the two?
Please also add information on Shimada data!

**Comment by talbrecht** [comment]
http://imbie.org/imbie-2016/drainage-basins/ ?

**Comment by talbrecht** [comment]
Please find a new download link, http://homepages.see.leeds.ac.uk/~earkhb/Basins_page.html is not working any more

**Comment by talbrecht** [comment]
Add calculate_reference_saar.py to README.md and update info on gsw installation, e.g. conda install -c conda-forge gsw

**Comment by flocolleoni** [comment]
You can download basins from here:
https://icesat4.gsfc.nasa.gov/cryo_data/drainage_divides/Ant_ICESat_MODIS_Mask_1km.ascii.gz

Here is GMT6 to get Zwally drainage basins ready for remaping and other use
[Zwally_basins.gmt.zip](https://github.com/pism/pism-ais/files/3594573/Zwally_basins.gmt.zip)

. The script outputs lonlat polar stereogrpahic projected basins, and a similar file in cartesian coordinates.

**Comment by juliusgarbe** [comment]
It appears that the "icesat4" and "zwally" basin definitions more or less refer to the same thing, with the first being a slightly newer version of the latter containing some very minor changes (see [here](https://earth.gsfc.nasa.gov/cryo/data/polar-altimetry/antarctic-and-greenland-drainage-systems)).
At the end, the scripts in `basins_icesat4` and `basins_zwally` were downloading the same file but from different websites for the different points in time.

Meanwhile, all the links in these scripts do not work any more. Instead, the most recent version of the file containing the basin and mask definitions ("Ant_ICESat_MODIS_Mask_1km.ascii", last modified in Jan 2012) can be found in the above mentioned website (note that the [IMBIE website](http://imbie.org/imbie-3/drainage-basins/) also refers there). I've updated the link in the README in commit d506472831521b4713750b7ed11fb23747162ed6.

That said, it would be a great and certainly worthwhile effort to merge all scripts from the two directories into one in order to clean up a bit!

**Comment by juliusgarbe** [comment]
Done, see commit 012598fd3b1fcd11023dedf4cb9dac7376228216
